trigger:
  branches:
    exclude:
      - '*'

jobs:
- job: Build
  displayName: 'Build Docker Image'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - script: bash docker_build.sh
    displayName: 'Docker Build'

- job: Deploy
  displayName: 'Deploy Docker Image'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - script: bash docker_run.sh
    displayName: 'Docker Run'
