trigger:
  branches:
    exclude:
      - '*'

jobs:
- job: Build
  displayName: 'Build Docker Image'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - script: docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD) interviewregistry
    displayName: 'Docker Login'

  - script: docker build -t bestappever .
    displayName: 'Build Docker Image'

  - script: docker tag bestappever interviewregistry/bestappever:$(Build.BuildId)
    displayName: 'Tag Docker Image'

  - script: docker push interviewregistry/bestappever:$(Build.BuildId)
    displayName: 'Push Docker Image'

- job: Deploy
  displayName: 'Deploy Docker Image'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - script: docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD) interviewregistry
    displayName: 'Docker Login'

  - script: docker pull interviewregistry/bestappever:$(Build.BuildId)
    displayName: 'Pull Docker Image'

  - script: docker run -d -p 3000:3000 interviewregistry/bestappever:$(Build.BuildId)
    displayName: 'Run Docker Container'
